# Generated by Django 2.1.2 on 2018-10-14 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=200, verbose_name='email')),
                ('apelido', models.CharField(max_length=100, verbose_name='apelido')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('senha', models.CharField(max_length=30, verbose_name='senha')),
                ('celular', models.IntegerField(max_length=30, verbose_name='celular')),
            ],
        ),
    ]
