# Generated by Django 2.1.2 on 2018-10-15 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='celular',
            field=models.CharField(max_length=30, verbose_name='celular'),
        ),
    ]
